# Environment
env_id: peg7x7
max_steps_per_episode: 150
train_episodes: 1000
eval_episodes: 10
eval_every: 50

# DQN
gamma: 0.99
lr: 0.0003
batch_size: 128
replay_capacity: 50000
learning_starts: 1000
target_update_interval: 1000

# Exploration
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay_steps: 50000

# Misc
seed: 42
device: cpu
artifacts_dir: artifacts/models/peg/dqn
# run_id: optional, if omitted a timestamp will be used

