# Training loop
max_steps_per_episode: 150
train_episodes: 1000
eval_every: 50

# Misc
seed: 42
device: cpu

# Console printing (set to true to see logs in terminal)
print_episode: false
episode_log_interval: 1
print_eval: true
